import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  >
      <body className={inter.className} >


      <header className="flex items-center justify-between p-4 bg-purple04 text-white h-20 fixed top-0 left-0 right-0 z-50">
  <h1 className="text-xl font-semibold">HoroWhisper</h1>
</header>





        {children}
      </body>
    </html>
  );
}
